version: '3.8'
services:
  SFIA1:
    build: ./
    image: rwright1992/sfia1:latest
    ports:
    - target: 5000
      published: 5000
      protocol: tcp
    environment:
      DATABASE_URI: ${DBURI}
      MY_SECRET_KEY: ${MYSECRETKEY}