version: '3.8'
services:
  SFIA1:
    image: rwright1992/sfia1:latest
    build: ./
    ports:
    - target: 5000
      published: 5000
      protocol: tcp
      enviornment:
        DATABASE_URI: ${DBURI}
        MY_SECRET_KEY: ${MYSECRETKEY}